version: '3.8'

services:

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: callmasters
    ports:
      - "15444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: ../
      dockerfile: devops/Dockerfile
    container_name: callmasters_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: callmasters
      APP_HOST: 0.0.0.0
      APP_PORT: 8075
      APP_API_PREFIX: v1
    ports:
      - 8075:8075

volumes:
  postgres_data:
