services:
  db:
    image: mysql
    env_file: ".env"
    container_name: db
    command: --init-file /basic/init.sql
    volumes:
      - mysql_db:/var/lib/mysql
      - ./init.sql:/basic/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55


  fastapi:
    build: .
    container_name: "fastapi"
    ports:
      - "8085:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_db: